pipeline:
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
    - stage:
        name: docker-image
        identifier: dockerimage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8sconnector
              namespace: harness-ci
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: barfielddockerconnector
                    repo: bissinc/harness-gohelloworldserver
                    tags:
                      - v1.1.111
    - stage:
        description: ""
        failureStrategies:
          - onFailure:
              action:
                type: StageRollback
              errors:
                - AllErrors
        identifier: deployharnesshelloworld
        name: deploy-harness-helloworld
        spec:
          deploymentType: Kubernetes
          environment:
            environmentRef: production
            deployToAll: false
            infrastructureDefinitions:
              - identifier: test_kubesmart_io
          execution:
            rollbackSteps:
              - step:
                  identifier: rollbackRolloutDeployment
                  name: Rollback Rollout Deployment
                  spec:
                    pruningEnabled: false
                  timeout: 10m
                  type: K8sRollingRollback
            steps:
              - step:
                  identifier: rolloutDeployment
                  name: Rollout Deployment
                  spec:
                    pruningEnabled: false
                    skipDryRun: false
                  timeout: 10m
                  type: K8sRollingDeploy
          service:
            serviceRef: harnessIohelloworldservice
        tags:
          4cd66115-08c5-4871-af72-c15064bc73df: ""
        type: Deployment
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: harnessrsasshkeytest
        repoName: GoHelloWorldServer
        build: <+input>
        sparseCheckout: []
  identifier: harnesstestproject0002
  name: harness-test-project-0001
