---
apiVersion: v1
kind: Service
metadata:
  name: harness-helloworld-service
  labels:
    k8s-app: harness-hellworld
  namespace: harness-ci
spec:
  selector:
    k8s-app: harness-helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-helloworld
  labels:
    k8s-app: harness-helloworld
  namespace: harness-ci
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: harness-helloworld
  template:
    metadata:
      labels:
        k8s-app: harness-helloworld
    spec:
      containers:
        - name: harness-gohelloworldserver
          image: bissinc/harness-gohelloworldserver:v187
          ports:
            - containerPort: 8080
---
apiVersion: v1
items:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        "cert-manager.io/cluster-issuer: letsencrypt-prod"
        "nginx.ingress.kubernetes.io/ssl-redirect: true"
      name: ingress-harness-helloworld
      namespace: harness-ci
    spec:
      ingressClassName: nginx
      rules:
        - host: harness-helloworld.test.kubesmart.io
          http:
            paths:
              - backend:
                service:
                  name: harness-helloworld-service
                  port:
                    number: 80
            path: /
            pathType: ImplementationSpecific
      tls:
        - hosts:
            - harness-helloworld.test.kubesmart.io
          secretName: harness-helloworld-ingress-tls
kind: List
metadata:
  resourceVersion:
